# Generated by Django 4.1.6 on 2023-02-09 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee', models.CharField(default=None, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('position', models.CharField(choices=[('Senior Recruiter', 'senior recruiter'), ('Recruiter', 'recruiter'), ('Associate', ',associate')], default='recruiter', max_length=100)),
                ('employee_commission', models.DecimalField(decimal_places=4, default=0.075, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('candidate', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('job_description', models.CharField(default=None, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('pay_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('charge_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('custom_commission', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('employee_commission', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('margins_plit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tid', models.CharField(default=None, max_length=250, null=True, unique=True)),
                ('split_employee', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='timesheets.employee')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='mylogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=8000, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('userid', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheets',
            fields=[
                ('timesheet_key', models.CharField(default=None, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('entry_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('units', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day')], max_length=10)),
                ('pay_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('charge_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('employee_commission', models.DecimalField(decimal_places=4, default=0.05, max_digits=12)),
                ('margins_plit', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('pay_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('charge_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('fx_date', models.DateTimeField(null=True)),
                ('invoice_sent', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('commission_processed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('hours', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('gross_pay_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('gross_charge_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('gross_pay_rate_gbp', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('gross_charge_rate_gbp', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('margin', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='timesheets.employee')),
                ('job', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheets.jobs')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=250, null=True)),
                ('candidate_start_date', models.DateTimeField(default=None)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('commission_ts_week_commencing', models.DateTimeField(default=None)),
                ('commission_total_hours', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('commission_gp_per_hour_gbp', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('commission_pay_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('commission_charge_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('commission_original_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('commission_charge_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('commission_fx_rate_to_gbp', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('commission_fx_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='timesheets.employee')),
                ('job_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timesheets.jobs')),
                ('timesheet_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timesheets.timesheets')),
            ],
        ),
    ]
